### ISSUE TITLE
 ERR_PNPM_NO_SCRIPT  Missing script: custom-bundle

### ISSUE THREAD

**Issue by sefgit** [flojoy-ai/studio#1070]
Trying to build flojoy-studio@v0.1.26 I got:

`
(flojoy) D:\flojoy\src\studio>pnpm run bundle-plotly

> flojoy-studio@0.1.26 bundle-plotly D:\flojoy\src\studio
> cd node_modules/plotly.js && pnpm install && pnpm run custom-bundle -- --traces scatter,scatter3d,surface,table,histogram,image,bar,indicator,heatmap

Already up to date
Done in 1.1s
 ERR_PNPM_NO_SCRIPT  Missing script: custom-bundle

Command "custom-bundle" not found.
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by itsjoeoui** [comment]
Hey @sefgit, could you try using either 
- `electron-package:windows` 
- `electron-package:mac` 
- `electron-package:linux` 
depending the platform you are on, to package it? Let me know if that works for you :)

**Comment by sefgit** [comment]
electron-package:windows works for me.

**Comment by itsjoeoui** [comment]
Awesome, feel free to raise another issue if you encounter any problem! We are always on Discord to help as well: https://discord.gg/7HEBr7yG8c :)
