### ISSUE TITLE
Node modals should show plotly charts

### ISSUE THREAD

**Issue by youngsun4786** [flojoy-ai/studio#490]
For every node a chart should be showing on the modal.

**Comment by JeffDotPng** [comment]
![image](https://github.com/flojoy-io/studio/assets/47371088/58df13de-a708-47f0-93c0-aa282fdec2db)
This is already implemented is it not?

**Comment by youngsun4786** [comment]
According to @smahmed776, the plotly charts should also be showing on the node modal. Please lmk if I am wrong @smahmed776!

**Comment by smahmed776** [comment]
> According to @smahmed776, the plotly charts should also be showing on the node modal. Please lmk if I am wrong @smahmed776!

I was referring to what @JeffDotPng mentioned here. At that time these charts were missing in node modals.
