### ISSUE TITLE
make node colors & shapes consistent and visually meaningful

### ISSUE THREAD

**Issue by jackparmer** [flojoy-ai/studio#628]
Currently there are 5 top-level node categories:
- Data
- I/O
- ETL
- Logic
- Autogenerated ("Autogen")

To make it easier to associate nodes with their functional category, their coloring and shapes should be meaningful, distinctive, and consistent.

I propose the color and shape scheme below

# Studio canvas

<img width="949" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/da00d262-b596-485d-bf34-1c58c96f6367">

# Docs sidebar

<img width="955" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/840e5162-8657-45d8-983f-7328929406c9">

# Docs sidebar when fully collapsed

<img width="949" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/36e58afb-aec0-46e1-ab33-b37984b2bf92">

# Studio sidebar

<img width="955" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/2840aed5-748a-4b1c-8732-97c18b7c9188">

# Previous studio canvas mocks (for comparison)

<img width="952" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/b51246d6-ee2a-4253-974d-8ddd3573f1e8">

**Comment by jackparmer** [comment]
# SVG icons

![Pyramid_953](https://github.com/flojoy-io/studio/assets/1865834/d91c05a7-5a60-4f46-9fd1-67802edd269e)

![Cuboid_949](https://github.com/flojoy-io/studio/assets/1865834/fde25569-a64d-41ad-b165-ec5f40339bb0)

![Icosahedron_995](https://github.com/flojoy-io/studio/assets/1865834/c3089982-31fb-4619-9135-8d98bac2d616)

![Cylinder_563](https://github.com/flojoy-io/studio/assets/1865834/45f6d397-be26-4d2f-97e8-84ad1e0c9da1)

**Comment by trbritt** [comment]
BTW the SVGs used for the NumPy and SciPy autogenerated nodes are hardcoded https://github.com/flojoy-io/studio/blob/main/src/feature/flow_chart_panel/svgs/add-multiply-svg.tsx#L130, just FYI

**Comment by scorinaldi** [comment]
Note: Node styling will have to be updated in the docs renderer also

**Comment by jackparmer** [comment]
# Nodes navigation home page on docs

## Dark theme

<img width="1235" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/007df24f-f36f-4e29-a397-bb7566411d79">

<img width="1235" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/c88c8166-f299-4bcd-afec-8afc3c970603">

<img width="1234" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/01da7025-7561-4a6c-a6da-db373f1c34a9">

<img width="1229" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/31864cb6-3a38-46ba-ad93-8142081ae5b9">

## Light theme

<img width="1237" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/8a6094b3-2dfb-47c4-8bce-3c23ccc33d13">

<img width="1236" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/f4153c20-83c2-4fcc-95b1-70ac3c88136b">

<img width="1238" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/8ea4dc60-5d54-4434-b1ee-1169fad5ad2f">

<img width="1236" alt="image" src="https://github.com/flojoy-io/studio/assets/1865834/763934bf-d772-4b0b-a1fa-5645458ea82c">
