### ISSUE TITLE
[x-post] UX first impressions on Studio, Cloud, and Docs

### ISSUE THREAD

**Issue by jackparmer** [flojoy-ai/studio#859]
Thoughtful UX first impressions and ideas from @jjerphan (reposted here for hackmd broader visibility)

https://hackmd.io/z779aJcNT62_dWfz-NmQ4A?both

Flojoy
======

# Feedback

## UX: valuable elements to keep

 - :star: :star: Ease of development and on-boarding (a simple command to launch Flojoy)
 - :star: A light and reactive application
 - :star: Good default keyboard shortcuts
 - :star: The inspection of Nodes' code with the direct access to GitHub
 - :star: Being able to request Node from the UI is incredibly convenient
 - The intuitiveness of Nodes
 - The affordance for unsaved project (small little dot at the top left corner)

### :bulb: Have the same behavior for "Backspace" and "Delete": delete elements on the graph

**Context**

For now, only "Backspace" actually deletes Node, while it feels that "Delete" also should.

**Proposed solution**

Also add this shortcut for this Keyboard Key.

### :bulb: Verbose reported status for pre-jobs

**Context**

For now, when the graph is being executed, "pre-jobs" are run for setting up necessary artifacts and objects for the nodes execution. The current execution only reports the "pre-jobs" as being run, without giving details about their execution. Some information is given in the logs of the execution of pre-jobs which are being reported in the terminal, but users (and even potentially nodes developers) won't have access to them especially with the self-contained Electron Client.

With the absence of feedback, users do not know if Flojoy has crashed or has freezed. Curious users also might want to know and understand what those pre-jobs consists in.

**Proposed solution**

Having information about the execution of pre-jobs would be valuable for users

Desirable feature:
 - A report of progress on pre-jobs executions (e.g "[1/10] Executing pre-job: Virtual Environment creation for Node A").
 - (Ideal) A detail about each pre-job execution

### :bulb: UI: Smaller Header and different menu

For header takes in between 10% to 15% of the usable screen. It feels like it could take less of it (i.e. 10% max).

Also the Node menu on the left feel a bit weird (one has to unfocus its vision on the center of the flow to search for nodes, on the long term, I think this might tire the eyes). I prefer the UX of the search on the documentation (or like the one on MacOS) with a general fuzzy search for a Nodes which is centered (hence no eyes nor hands movement are required, only keystrokes).

### :bulb: Windows' menu for loading local files

Less error prone and manually entering a string.

### :bulb: Pause/Resume button

**Context**

For now, it is only possible to Play and to Stop (i.e. abort the execution) of the graph. For various reasons, users might want to pause the execution of their flow (e.g. when they are context switching with other task, of if they want to inspect / debug the result of a node).

**Proposed solution**

Have finer control over the graph or specific Nodes' execution.

Desirable features:
 - (Core) Pause and Resume the overall execution of the graph
 - (Ideal) Have break point settable on Nodes (for debugging purposes)

### :bulb: Load last saved application/project and recent projects' list

**Context**

Currently, there is no way of keeping track of the last projects which have been opened within Flojoy. One needs to specify the project to use at the start of Flojoy.

Also one cannot load another project when Flojoy is already being used without (force) reloading Flojoy.

**Proposed solution**

- (Core) Have a list of the latest project which have been

### :bulb: Uploads to Flojoy Cloud

**Context**

Flojoy allows uploading DataContainers under Measurement on Flojoy Cloud. Each measurement can have several DataContainers published.

The current error message aren't explaining why measurement ID aren't valid when that's the case; one currently get the following error message:

> "You must provide a valid measurement id in order to upload to Flojoy Cloud!""

Also it might take some time for users to understand how to setup measurements and where to find their ids. Also, users might want to specify meta-data for each records of measurement.

**Proposed solution**

 - (Core) Introduce comprehensive error message so that users can understand why the measurement id is faulty
 - (Nice-to-have) Propose the creation of a measurement for an unknown measurement ID.
 - (Ideal) Be able to specify meta-data for measurement records

### :bulb: Double click to edit text boxes.

**Context**

One needs to click a small button to edit the text, whereas it is actually simpler to just double click on the text boxes to edit the text.

**Proposed solution**

Make double click edit text boxes.

### :bulb: App versioning using git

**Context**

Apps are saved as simple JSON files. While this is relatively easily and versatile to work with, it does not prevent people from crashing their entire project, which might cause a lot of stress and cost.

Users definitely would have some peace of mind if they know they can experiment without strew up the current state by being able to get back to its previous versions. Also if different people were to work on the same application, one would need to keep track of modification made by several people.

**Proposed solution**

Being able to version project would solve those problems.

Desirable features:
 - (Core) Minimal support of project versioning using git
     - As a user of Flojoy and git:
         - I would ideally would like to commit changes at the level of a Node with a comprenhensive commit message on several lines.
         - I would also ideally like to have access to the git repository to perform manual inspection of the history of the project.
 - (Nice to have) Integration UI with GitHub
 - (Ideal): Diff rendering between two revisions (for conflict resolution)

### :bulb: Improve Text View rendering

**Context**

The current Text View rendering is relatively simple, but its rendering can't be changed by users. As a result, it sometimes does not entirely show the text, and does not occupy the space properly on the project canvas.

**Proposed solution**

Let users change the rendering of the Node on the Front-End.

 - (Core) Change the shape of the Node
 - (Core) Change the size of the text

### :bulb: Support Undo/Redo

**Context**

Undo/Redo is present in the menu of the UI, but is not usable yet.

**Proposed solution**

Make it possible to undo and redo the last actions.

### :bulb: Documentation button should redirect to the online documentation

For now, the Documentation button redirects to [the documentation of Electron](https://github.com/electron/electron/tree/v24.7.1/docs#readme) it must instead redirect to [the documentation of Folly](https://docs.flojoy.ai/getting-started/install/?platform=unix).

### :bulb: Consistency of the editorial policy for existing Nodes

**Context**

I think Nodes might have been developped with different use-cases or and goals in mind. It feels like there are two kinds of Nodes:
 - **Coarse-grained Nodes**: Some Node have been developed with topical use-cases (such `DEEPLAB_V3` for Image Segmentation).
 - **Fine-grained Nodes** Some other Nodes have been developped as matching existing APIs in libraries (e.g. `CHOLESKY` for porting `np.linalg.cholesky`).

Also some Nodes might have been duplicated, this might be for instance the case of:
 - `LOAD_IMAGE` and `OPEN_IMAGE` (if it is no the case, it is not intuitive to know their difference and when one has to use the first or the second one)
 - Nodes under "Transform" and "NumPy"

Moreover, whilst most nodes are intuitive to use, some aren't. For instance:
- `DS_NODE` has not an explicit name, and it is not clear to know what it until reading [its documentation](https://docs.flojoy.ai/nodes/LOADERS/INTERNAL_MEMORY/DS_LOAD/) ("Ah `DS` is a short for Data Storage, which seems to be a way to store data generally in a in-memory store. How can this be useful for my use-cases? Am I meant to even use that?")

**Proposed solution**

 - Have only a few but valuable nodes based on users' needs (I believe that "Less is More"). Potentially this means focusing the development on (a few) coarsed-grained Nodes rather than one (a lot of) fine-grained Nodes. Carefully weight the value of each new Node as each Node comes with maintainance costs and additional information for users').
 - Organize the Nodes sections on "Use-Cases" or "Applications".
 - Add "Labels" for Nodes to improve their discoverability (e.g. have Nodes be labelled as relevant for given applications so that one can filter Nodes based on their applications).
 - Develop a Community around Nodes and Apps for Flojoy. I think HuggingFace Hub manages it really well: people can publish models, datasets with the same spirit of GitHub, have their profile, are part of organizations, are proud to publish and share their creations and have them be forked and improved. This can also help Flojoy grow organically, reach users.

## About the documentation

:100: I really like the short-cut for searching nodes: it is convenient _and_ effective. 

:100: I really like the Apendix section, with the possibility to add "Theory and technical notes" and "Media" via contributions on GitHub.

:confused: I find that the background of the documentation pages, with square is disruptive and makes the text harder to read. If I were to choose, I would simply remove them and keep a uniform background everywhere (in the menu on the left, in the body of the page, and in the column on the right.

:bulb: "General Tutorials" might be costly to maintain at this point (in my experience updating screenshots and keeping consistency is costly) and you might want to be able to iterate relatively quickly without having to maintain such material for now. Also I think good software is intuitive software which does not need any documentation for it to be understandable and effectively usable. To me, this is the case of Flojoy. IMO, energy might better be spend on solving usability problems and developing Nodes based on use-cases of prospects and users.
:warning: Note that I am biased since I am the kind of user who does not need tutorial and who jumps straight into the usage or the code, so my point of view  might not be representing targeted users'.

## About performance

 - (Not urgent, might be important) Separation of images' channels might be a problem for performane in long pipeline since it necessitates stacking slices of numpy arrays together. This might create supplementary memory allocation, which might cause slower application with a larger memory usage.

**Comment by jjerphan** [comment]
As proposed by and discussed with @itsjoeoui on Friday, each item has been moved to Linear so that it can be tracked and discussed independently.

**Comment by itsjoeoui** [comment]
Thanks! @jackparmer. Yep as discussed with @jjerphan, we will keep track of all the suggestions on Linear 👌

**Comment by itsjoeoui** [comment]
I will close this for the moment
