### ISSUE TITLE
[STU 189] - RFC - Reactive Flojoy

### ISSUE THREAD

**Issue by TheBigSasha** [flojoy-ai/studio#967]
**the project proposed in this RFC has entered active development, please read newer RFCs titled "reactive", as this one is not up to date with the latest design decisions.**

Reactive rewrite project code repo : https://github.com/flojoy-ai/studiolab

# Reactive Nodes

Purpose: To improve the way live and continuous data is handled in flojoy, to allow for more efficient processing of data streams and event based programs.

# Implementational Details 
**_Please note that these details have not been updated since the implementation in studiolab. If there is a discrepancy, please comment. Thanks!_**
A Reactive node's basic anatomy is as follows:
- It has two generic types: In and Out representing the inputs and outputs of the underlying function (like the ones defining nodes today)
- It watches an input observable AKA subject which fires an event when a new datum is ready for processing
- It has a queue (created in `buffer_with_count`) which contains the next inputs it will processs
- It exposes observables for its current state which can be used for orchestration and UI updates

The run function is stateless, and acts exactly like the current flojoy nodes

Although I use a typescript-like pseudocode, remember the actual code for all this will be in Python

```
interface ReactiveNodeStatus {
  error?: Error,
  state: "Waiting" | "Processing" | "Finished" | "BufferOverflow",
  nodeID: UUID,
}

interface ReactiveNodeDefinition<In, Out> {
  input: Subject<In>,
  run: (In) => Out,
  lossy?: boolean, // allow for loss of incoming data to process the lastest input in realtime
  garunteeOrder?: boolean, // allow to execute in parallel, out of order to improve performance but lose the invariant of input order
  maxQueueSize: number // How big can the input buffer be before we start losing data
}

interface ReactiveNode<In, Out> {
  input: Subject<In>,
  output: Subject<Out>,
  status: Subject<ReactiveNodeStatus>,
}

function buildReactiveNode<In, Out>({lossy, garunteeOrder, maxQueueSize, run, input}: ReactiveNodeDefinition) => ReactiveNode<In, Out> {
    // Create input, output observables based on the lossy, garunteeOrder, maxQueueSize params
    
    pipe = input.pipe(
      ops.observe_on(scheduler), // run on separate threads if wanted
      ops.buffer_with_count(maxQueueSize), // queue up unprocessed events
      // can add more pipeline features here to improve and customize reactive processing
    );
  

    pipe.subscribe(val => {
         status.emit({state: "Processing"}); 
           try{
            const out = run(val);
            output.emit(out);
            status.emit({state: "Finished"});
          } catch (e) {
              status.emit({state: "Finished", error: e.message});
          }
     });
 }
```

# Nodes <=> Other Nodes

Nodes are wired up by walking the node graph. Nodes with no in edge watch the FlojoyFlowchartRun observable, which fires when the user presses play.
```
// already declared vars: runObservable: Subject<Bool>, finishObserver: Subject<Any>, handleCycles: a function which resolves issues with cycles

function wireUpRec(node: Node){
  if handleCycles(node):
    return handleCycles(node)

  wired = match node with:
    no inputs -> buildReactiveNode(input = runObservable) // this case wires up an input node to the base input
    n inputs -> buildReactiveNode(input = zip(node.inputs.map(wireUpRec)) // When we have many inputs, zip & buffer to garuntee order
      // in the n inputs case we can also not buffer if the garunteeOrder flag is false
      // When we have inputs, we recursively wire them up, they will eventually return their output observers

  return wired.output
}

function buildNodeGraph(nodeGraph: NodeGraph){

  const islands = separateUnconnectedGraphs(nodeGraph)

  const wired = islands.map(graph => {
    const terminalNodes = findNodesWithoutOutEdges(nodeGrpah)
    // we do a reverse traversal to wire up the execution graph here
    // This line is a lot. First it converts each node to an observable using `map` then it subsribes each terminal node to the finish observer
    const wired = terminalNodes.map(wireUpRec(node)).forEach(wired => finsihObserver.subscribe(wired));
   })

  finishObserver.subsribe((node) => node.on_completed());
}
```

After these functions execute, we have built a graph of observables with the following properties:

- Each island of the graph will begin executing on events of the runObservable
       - The MVP version of this would have the play button in flojoy studio trigger an event on the runObservable subject. Later versions can replace this with any event, IE triggering the flowchart's execution on a button press, network request, ROS event, etc.
- When terminal nodes finish, they will fire notify the finishObserver
- Each node will:
       - Take input of the zip of all of its upstream nodes
       - Emit its output to its downstream nodes
       - Handle its execution according to the params in buildReactiveNode
- During graph creation, we can also throw in more handlers for various events for features like exception handling and UI

*Parallel Execution & Order / Completeness Garuntees*

- Sometimes, we want a slow observer to execute each and every request from an upstream fast observable (IE typical current flojoy nodes)

- There are times when we want downstream nodes to run in parallel, to improve performance.
```
# Create a ThreadPoolScheduler to run each observer on a separate thread
pool_scheduler = ThreadPoolScheduler(2)

# Create a Subject
subject = Subject()

# Create an Observer
observer = subject.pipe(
    ops.observe_on(pool_scheduler),  # Ensure observer runs on separate thread
    ops.buffer_with_count(10)  # Buffer 10 items at a time
).subscribe(
    on_next=lambda x: print(f"Processed {x}"),
    on_error=lambda e: print(f"Error Occurred: {e}"),
    on_completed=lambda: print("Processing Completed")
)

# Emit items faster than observer can process
for i in range(100):
    subject.on_next(i)
    time.sleep(0.01)  # Emit every 0.01 seconds

# Complete the subject
subject.on_completed()
```
In this example, we emit events in a way that is faster than what we can process, but we handle it by using a buffer_with_count to make sure that up to ten items in backlog are processed in order without omission. 

# UI Rendering

UI rendering will be handled 100% reactively. A singleton observer called the FlojoyUIObserver will subscribe to status of every node created in BuildNodeGraph This observer will fire a websocket event for each event it sees. The frontend will then subsequently render the update, updating the node in the flowchart.

The UI observer will react to the status changes of every node in the flowchart

The UI observer will send a websocket message to the frontend containing the ID of the node that changed and its new status. At this stage batching can be implemented to send bigger UI updates with a limited frequency (IE gather flowchart changes for 0.1s, aggregate them, and send the UI update to the frontend at 10hz)

The frontend will re-render due to websocket

Additional Node Metadata

- In addition to I/O types, reactive nodes would have more powerful features configurable in metadata as well:

-  `lossy`  -  if enabled, the node will process the latest of its inputs instead of processing them in order (input buffer size of 1)
      - Improves responsiveness and performance at the cost of data consistency. Good for inputs IE potentiometer or a connection status

- `garunteeOrder` - (true by default) - if enabled, this node's inputs will be queued with a sufficiently large buffer and will be executed in order. Disabling this allows the node to be executed in parallel.

**Comment by TheBigSasha** [comment]
Quick note, this is an older RFC, and was turned already into the studio lab project as of October / November. Much of the info in this RFC is obsolete in lieu of changes in the future reactive related RFCs or implanted changes in studiolab.

> How do the "Reactive node's basic anatomy" and the pseudo-code you have indicated relate to one another. How is a ReactiveNodeDefinition different from a ReactiveNode?

The code here is just high level pseudocode which is quite loosely intertwined. I think of the defintion class as a signature / interface while the node class is implemented. The real code is in studiolab and a new RFC for reactive node dx. 

> By Subject, do you mean Topic?
Not exactly. Topics in ROS are similar but subject is a more specific construct from the reactiveX library. It's like an observer / observable if you're familiar with Java builtins.

> Is the latest paragraph of the "Additional Node Metadata" redundant with what is being presented in the first "Implementational Details" section? I would suggest implementing and documenting all the elements of the abstractions for the Reactive Nodes with comments directly and explicitly.

Agreed, good point on this. I have worked on addressing this with the current RFCs (as this one is all implemented or changed now), but please do let me know if there are some specific improvements you can see in light of those newer RFCs :)

> Moreover, I have a few suggestions and question:
> 
> What is the role of the runObservable and the role of the finishObserver? Can you give reference for their semantics?

The execution flowchart is in the form of a bunch of subjects subscribing to and publishing to each other. Without an initial input, this system will never start, because the input side unconnected blocks won't ever get an input and therefore start the chain reaction. The run observable provides that signal to the blocks with an in degree of 0. The finish observable is attached to any present but unconnected block outputs, handling when they change. If the flowchart is started only by run and has no stateful blocks (see the related RFC), the finish observer would notify the UI that execution has completed. 

> For the "Parallel Execution & Order / Completeness Garuntees" part, I would suggest using concurrent.futures, or even joblib/loky which should be more robust

Great suggestion! When we move to performance optimization that would be an awesome tool to use.

> Can you indicate the library you are intending to use?

The library used in studiolab is ReactiveX (RxPy). It was chosen because it's well supported and maintained, familiar to developers, and it's available in many languages which can allow flexibility by re writing the executor in a lower level language in the future for improved speed.

**Comment by jjerphan** [comment]
Thank you for this comprehensive reply, @TheBigSasha!

On Loky: Loky is not (just) relevant for performance improvement, but rather for resilient workflow. Loky has been developed as a robust back-end for joblib which is used by several libraries in the Scientific Python ecosystem.

For instance, see [how Dask can uses Loky for its Workers to ensure resilient execution preventing problems](https://www.youtube.com/watch?v=vF2VItVU5zg).

For even more details, see [this piece of documentation](https://github.com/joblib/loky/blob/05da9a84b6bae8dd4370f553ffcd06df99b54f86/loky/process_executor.py#L15-L55).

I will comment the other RFCs.

If this works for you, I let you close this issue as completed. :slightly_smiling_face:

**Comment by TheBigSasha** [comment]
> Thank you for this comprehensive reply, @TheBigSasha!
> 
> On Loky: Loky is not (just) relevant for performance improvement, but rather for resilient workflow. Loky has been developed as a robust back-end for joblib which is used by several libraries in the Scientific Python ecosystem.
> 
> For instance, see [how Dask can uses Loky for its Workers to ensure resilient execution preventing problems](https://www.youtube.com/watch?v=vF2VItVU5zg).
> 
> For even more details, see [this piece of documentation](https://github.com/joblib/loky/blob/05da9a84b6bae8dd4370f553ffcd06df99b54f86/loky/process_executor.py#L15-L55).
> 
> I will comment the other RFCs.
> 
> I let you close this issue as completed. 🙂

Thanks for the heads up on loky, I'll forward that info to the reactive / studiolab chat on Slack. Much appreciated :) Though we'll have to look into interop with RX.
